### ISSUE TITLE
Automate homebrew formula updates

### ISSUE THREAD

**Issue by aaronshurley** [vmware-tanzu/homebrew-carvel#15]
To reduce ongoing maintenance, it would be great if we automated homebrew formula updates. It looks like [GoReleaser](https://goreleaser.com/customization/homebrew/) is a fairly common solution.

**Comment by benmoss** [comment]
This looks to have been done by this workflow: https://github.com/vmware-tanzu/carvel-release-scripts/blob/main/.github%2Fworkflows%2Fpublished_release.yml
