### ISSUE TITLE
Homebrew tap URL doesn't work

### ISSUE THREAD

**Issue by ProNibs** [vmware-tanzu/homebrew-carvel#36]
https://github.com/carvel-dev/homebrew-homebrew/ seems to not exist

**Comment by tiansiyuan** [comment]
I met the same issue.

% brew tap carvel-dev/homebrew
==> Tapping carvel-dev/homebrew
Cloning into '/usr/local/Homebrew/Library/Taps/carvel-dev/homebrew-homebrew'...
Username for 'https://github.com': tiansiyuan
Password for 'https://tiansiyuan@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/carvel-dev/homebrew-homebrew/' not found
Error: Failure while executing; `git clone https://github.com/carvel-dev/homebrew-homebrew /usr/local/Homebrew/Library/Taps/carvel-dev/homebrew-homebrew --origin=origin --template=` exited with 128.

**Comment by praveenrewar** [comment]
Thanks for the issue @ProNibs and @tiansiyuan! 
The command should be `brew tap carvel-dev/carvel` or `brew tap carvel-dev/homebrew-carvel`, I will update the README and the docs accordingly.
